// swift-tools-version: 5.9
// Generated by scripts/write_package_manifest.sh. Do not edit by hand.
import PackageDescription

// Two variants share the SleepCycleSDK module (import SleepCycleSDK):
//   • SleepCycleSDK     — models embedded (works offline, larger).
//   • SleepCycleSDKSlim — models downloaded at runtime (smaller).
// Depend on exactly one product; both vend the SleepCycleSDK module.
// The frameworks link and load on iOS 13; the SDK API is annotated @available(iOS 16.0, *).
let package = Package(
    name: "SleepCycleSDK",
    platforms: [
        .iOS(.v13),
        .macOS(.v13)
    ],
    products: [
        .library(name: "SleepCycleSDK", targets: ["SleepCycleSDK", "SleepCycleObjC"]),
        .library(name: "SleepCycleSDKSlim", targets: ["SleepCycleSDKSlim", "SleepCycleObjC"])
    ],
    targets: [
        .binaryTarget(
            name: "SleepCycleSDK",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.1-beta2/SleepCycleSDK-1.4.1-beta2.zip",
            checksum: "c625f9166755690b94daa71135761db3fd4e60f3f5914e23aa7fda23a143ec38"
        ),
        .binaryTarget(
            name: "SleepCycleObjC",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.1-beta2/SleepCycleObjC-1.4.1-beta2.zip",
            checksum: "e53dee8d396cd6be8d7a5938fda85af2c81961daae68a0cb3d2e7e0101a6ce9e"
        ),
        .binaryTarget(
            name: "SleepCycleSDKSlim",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.1-beta2/SleepCycleSDKSlim-1.4.1-beta2.zip",
            checksum: "1f69bf43076fa6b70872d348a8f3829d42d8de91801699441967059139c54f01"
        )
    ]
)
