// swift-tools-version: 5.9
// Generated by scripts/write_package_manifest.sh. Do not edit by hand.
import PackageDescription

// Two variants share the SleepCycleSDK module (import SleepCycleSDK):
//   • SleepCycleSDK     — models embedded (works offline, larger).
//   • SleepCycleSDKSlim — models downloaded at runtime (smaller).
// Depend on exactly one product; both vend the SleepCycleSDK module.
// The frameworks link and load on iOS 13; the SDK API is annotated @available(iOS 16.0, *).
let package = Package(
    name: "SleepCycleSDK",
    platforms: [
        .iOS(.v13),
        .macOS(.v13)
    ],
    products: [
        .library(name: "SleepCycleSDK", targets: ["SleepCycleSDK", "SleepCycleObjC"]),
        .library(name: "SleepCycleSDKSlim", targets: ["SleepCycleSDKSlim", "SleepCycleObjC"])
    ],
    targets: [
        .binaryTarget(
            name: "SleepCycleSDK",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.0-beta3/SleepCycleSDK-1.4.0-beta3.zip",
            checksum: "81abcf9bb761cf74db899273f7b55e131b8bf419c24350b531792178995c20a0"
        ),
        .binaryTarget(
            name: "SleepCycleObjC",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.0-beta3/SleepCycleObjC-1.4.0-beta3.zip",
            checksum: "8b36fb44e2363aeda2afab7211fc594ca0cf44c160d0a9157a4bf13a76067028"
        ),
        .binaryTarget(
            name: "SleepCycleSDKSlim",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.4.0-beta3/SleepCycleSDKSlim-1.4.0-beta3.zip",
            checksum: "82278c2cefd694bcd6a1e6b373797b8b5b71afa1b1f2158d4ff66aa3746e26d8"
        )
    ]
)
