// swift-tools-version: 5.9
// Generated by scripts/write_package_manifest.sh. Do not edit by hand.
import PackageDescription

// Two variants share the SleepCycleSDK module (import SleepCycleSDK):
//   • SleepCycleSDK     — models embedded (works offline, larger).
//   • SleepCycleSDKSlim — models downloaded at runtime (smaller).
// Depend on exactly one product; both vend the SleepCycleSDK module.
// The frameworks link and load on iOS 13; the SDK API is annotated @available(iOS 16.0, *).
let package = Package(
    name: "SleepCycleSDK",
    platforms: [
        .iOS(.v13),
        .macOS(.v13)
    ],
    products: [
        .library(name: "SleepCycleSDK", targets: ["SleepCycleSDK", "SleepCycleObjC"]),
        .library(name: "SleepCycleSDKSlim", targets: ["SleepCycleSDKSlim", "SleepCycleObjC"])
    ],
    targets: [
        .binaryTarget(
            name: "SleepCycleSDK",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.5.1/SleepCycleSDK-1.5.1.zip",
            checksum: "e98aac89e3b4498952f674f7cbda8b9437f3df773c39eb65f6c18a846f30939d"
        ),
        .binaryTarget(
            name: "SleepCycleObjC",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.5.1/SleepCycleObjC-1.5.1.zip",
            checksum: "cf5fd56494fe292212be3cebe7f6e92221f4917bdc6508cef40995a074c38734"
        ),
        .binaryTarget(
            name: "SleepCycleSDKSlim",
            url: "https://github.com/MDLabs/sleepcycle-sdk-swift/releases/download/v1.5.1/SleepCycleSDKSlim-1.5.1.zip",
            checksum: "a8f3427d3608996bd9a0e43df4b1f9ea1ec0e6d3b48292ed343fb2f743d5f014"
        )
    ]
)
